export const serviceDetails: Record<string, any> = {
  scanning: {
    titleEn: "Document Scanning & Digitization",
    titleTh: "สแกนเอกสารและการแปลงดิจิทัล",
    descriptionEn: "Transform physical documents into high-quality digital files with precision and care.",
    descriptionTh: "แปลงเอกสารกระดาษเป็นไฟล์ดิจิทัลคุณภาพสูงด้วยความแม่นยำและการดูแล",
    overviewEn: "Our document scanning service uses state-of-the-art scanners and rigorous quality control to handle everything from standard office documents to oversized maps and fragile historical records. We deliver high-resolution digital files with advanced OCR technology ensuring your documents are both preserved and searchable.",
    overviewTh: "บริการสแกนเอกสารของเราใช้เครื่องสแกนที่ทันสมัยและการควบคุมคุณภาพที่เข้มงวดเพื่อจัดการเอกสารตั้งแต่เอกสารสำนักงานมาตรฐานไปจนถึงแผนที่ขนาดใหญ่และบันทึกทางประวัติศาสตร์ที่ละเอียดอ่อน",
    ctaText: { en: "Start Scanning Project", th: "เริ่มโครงการสแกน" },
    benefits: [
      { en: "High-resolution scanning up to 1200 DPI", th: "สแกนความละเอียดสูงถึง 1200 DPI" },
      { en: "Advanced OCR with 99.9% accuracy", th: "OCR ขั้นสูงที่มีความแม่นยำ 99.9%" },
      { en: "Multiple output formats: PDF/A, TIFF, JPEG2000", th: "รูปแบบเอาต์พุตหลายแบบ: PDF/A, TIFF, JPEG2000" },
      { en: "Automated indexing and metadata tagging", th: "การจัดทำดัชนีอัตโนมัติและการติดป้ายข้อมูลเมตา" },
      { en: "ISO 15489 compliant processes", th: "กระบวนการที่สอดคล้องกับ ISO 15489" },
      { en: "Secure chain of custody documentation", th: "เอกสารการรักษาความปลอดภัยของการควบคุม" },
    ],
    process: [
      { en: "Document Assessment", th: "การประเมินเอกสาร" },
      { en: "Pre-scanning Preparation", th: "การเตรียมการก่อนสแกน" },
      { en: "High-Quality Scanning", th: "การสแกนคุณภาพสูง" },
      { en: "OCR & Indexing", th: "OCR และการจัดทำดัชนี" },
      { en: "Quality Assurance Review", th: "การตรวจสอบการรับประกันคุณภาพ" },
    ],
    pricing: [
      {
        tier: "Standard",
        price: "0.50",
        currency: "฿/page",
        description: "For standard office documents",
        features: [
          "Up to 300 DPI resolution",
          "Basic OCR",
          "PDF format",
          "Standard turnaround: 5-7 days",
        ],
      },
      {
        tier: "Premium",
        price: "1.00",
        currency: "฿/page",
        description: "For high-quality archival scanning",
        features: [
          "Up to 600 DPI resolution",
          "Advanced OCR with language support",
          "Multiple formats (PDF/A, TIFF)",
          "Metadata tagging",
          "Turnaround: 3-5 days",
        ],
      },
      {
        tier: "Enterprise",
        price: 0,
        currency: "",
        description: "Custom solutions for large projects",
        features: [
          "Up to 1200 DPI resolution",
          "Multi-spectral imaging",
          "Full workflow automation",
          "Dedicated project manager",
          "Custom turnaround",
        ],
      },
    ],
    faqs: [
      {
        question: "What file formats do you support?",
        questionTh: "คุณรองรับรูปแบบไฟล์ใดบ้าง?",
        answer: "We support PDF, PDF/A, TIFF, JPEG, JPEG2000, and custom formats. PDF/A is recommended for long-term archival.",
        answerTh: "เรารองรับ PDF, PDF/A, TIFF, JPEG, JPEG2000 และรูปแบบที่กำหนดเอง ขอแนะนำให้ใช้ PDF/A สำหรับการจัดเก็บระยะยาว",
      },
      {
        question: "How long does scanning take?",
        questionTh: "การสแกนใช้เวลานานเท่าไร?",
        answer: "Standard projects take 5-7 days, Premium 3-5 days. Large projects are handled on a custom timeline.",
        answerTh: "โครงการมาตรฐานใช้เวลา 5-7 วัน Premium 3-5 วัน โครงการขนาดใหญ่จัดการตามกำหนดเวลาที่กำหนดเอง",
      },
      {
        question: "Is my data secure?",
        questionTh: "ข้อมูลของฉันปลอดภัยหรือไม่?",
        answer: "Yes. We maintain strict security protocols, encrypted storage, and secure destruction of originals upon completion.",
        answerTh: "ใช่ เรารักษาโปรโตคอลความปลอดภัยที่เข้มงวด การจัดเก็บที่เข้ารหัส และการทำลายต้นฉบับอย่างปลอดภัยเมื่อเสร็จสิ้น",
      },
    ],
  },
  electronic: {
    titleEn: "Electronic Document Management",
    titleTh: "การจัดการเอกสารอิเล็กทรอนิกส์",
    descriptionEn: "Implement comprehensive EDMS solutions that streamline workflows and ensure compliance.",
    descriptionTh: "ใช้งานโซลูชัน EDMS ที่ครอบคลุมเพื่อปรับปรุงขั้นตอนการทำงานและรับประกันการปฏิบัติตาม",
    overviewEn: "Our electronic document management systems integrate seamlessly with your existing enterprise infrastructure. We design custom workflows, implement role-based access controls, and ensure regulatory compliance across all document operations.",
    overviewTh: "ระบบการจัดการเอกสารอิเล็กทรอนิกส์ของเรารวมเข้ากับโครงสร้างพื้นฐานองค์กรที่มีอยู่ของคุณได้อย่างราบรื่น เราออกแบบขั้นตอนการทำงานที่กำหนดเอง ใช้งานการควบคุมการเข้าถึงตามบทบาท และรับประกันการปฏิบัติตามข้อกำหนดทั่วทั้งการดำเนินการเอกสาร",
    ctaText: { en: "Implement EDMS", th: "ใช้งาน EDMS" },
    benefits: [
      { en: "Enterprise EDMS implementation", th: "การใช้งาน EDMS ระดับองค์กร" },
      { en: "Automated approval workflows", th: "ขั้นตอนการอนุมัติอัตโนมัติ" },
      { en: "Role-based access control", th: "การควบคุมการเข้าถึงตามบทบาท" },
      { en: "Audit trails and compliance reporting", th: "บันทึกการตรวจสอบและรายงานการปฏิบัติตาม" },
      { en: "Integration with SAP, Oracle, ERP systems", th: "การรวมกับระบบ SAP, Oracle, ERP" },
      { en: "PDPA and regulatory compliance", th: "การปฏิบัติตาม PDPA และข้อกำหนดด้านกฎหมาย" },
    ],
    process: [
      { en: "Requirements Analysis", th: "การวิเคราะห์ความต้องการ" },
      { en: "System Design & Configuration", th: "การออกแบบและการกำหนดค่าระบบ" },
      { en: "Integration & Testing", th: "การรวมและการทดสอบ" },
      { en: "User Training", th: "การฝึกอบรมผู้ใช้" },
      { en: "Go-Live & Support", th: "เปิดตัวและการสนับสนุน" },
    ],
    pricing: [
      {
        tier: "Starter",
        price: "50000",
        currency: "฿/month",
        description: "For small teams (up to 50 users)",
        features: [
          "Basic EDMS functionality",
          "Up to 50 users",
          "5GB storage",
          "Email support",
        ],
      },
      {
        tier: "Professional",
        price: "150000",
        currency: "฿/month",
        description: "For growing organizations",
        features: [
          "Advanced workflows",
          "Up to 500 users",
          "100GB storage",
          "Priority support",
          "Basic integration",
        ],
      },
      {
        tier: "Enterprise",
        price: 0,
        currency: "",
        description: "Custom enterprise solutions",
        features: [
          "Full customization",
          "Unlimited users",
          "Unlimited storage",
          "24/7 dedicated support",
          "Full ERP integration",
        ],
      },
    ],
    faqs: [
      {
        question: "Can you integrate with our existing systems?",
        questionTh: "คุณสามารถรวมกับระบบที่มีอยู่ของเราได้หรือไม่?",
        answer: "Yes, we integrate with SAP, Oracle, Salesforce, and most enterprise systems. Custom integrations are available.",
        answerTh: "ใช่ เรารวมกับ SAP, Oracle, Salesforce และระบบองค์กรส่วนใหญ่ มีการรวมที่กำหนดเองให้ใช้ได้",
      },
      {
        question: "How long is implementation?",
        questionTh: "การใช้งานใช้เวลานานเท่าไร?",
        answer: "Typical implementation takes 8-12 weeks depending on complexity and integration requirements.",
        answerTh: "การใช้งานทั่วไปใช้เวลา 8-12 สัปดาห์ขึ้นอยู่กับความซับซ้อนและข้อกำหนดการรวม",
      },
      {
        question: "What about data migration?",
        questionTh: "การโยกย้ายข้อมูลเป็นอย่างไร?",
        answer: "We handle complete data migration from legacy systems with full validation and zero data loss.",
        answerTh: "เรารับผิดชอบการโยกย้ายข้อมูลที่สมบูรณ์จากระบบเดิมพร้อมการตรวจสอบที่สมบูรณ์และไม่มีการสูญหายข้อมูล",
      },
    ],
  },
  microfilm: {
    titleEn: "Microfilm Services",
    titleTh: "บริการไมโครฟิล์ม",
    descriptionEn: "Long-term document preservation with 500+ year lifespan under proper storage.",
    descriptionTh: "การอนุรักษ์เอกสารระยะยาวที่มีอายุการใช้งาน 500 ปีขึ้นไปภายใต้การจัดเก็บที่เหมาะสม",
    overviewEn: "Microfilm remains the gold standard for long-term document preservation. We provide complete microfilm services including creation, duplication, scanning, and reader maintenance. All services comply with ISO standards for archival quality.",
    overviewTh: "ไมโครฟิล์มยังคงเป็นมาตรฐานทองคำสำหรับการอนุรักษ์เอกสารระยะยาว เรามีบริการไมโครฟิล์มที่สมบูรณ์รวมถึงการสร้าง การทำสำเนา การสแกน และการบำรุงรักษาเครื่องอ่าน บริการทั้งหมดสอดคล้องกับมาตรฐาน ISO สำหรับคุณภาพหอจดหมายเหตุ",
    ctaText: { en: "Discuss Microfilm Solution", th: "พูดคุยเกี่ยวกับโซลูชันไมโครฟิล์ม" },
    benefits: [
      { en: "16mm and 35mm microfilm production", th: "การผลิตไมโครฟิล์ม 16 มม. และ 35 มม." },
      { en: "COM (Computer Output Microfilm) services", th: "บริการ COM (Computer Output Microfilm)" },
      { en: "Microfilm duplication and preservation", th: "การทำสำเนาและอนุรักษ์ไมโครฟิล์ม" },
      { en: "High-resolution microfilm scanning", th: "การสแกนไมโครฟิล์มความละเอียดสูง" },
      { en: "ISO 18901 and ISO 18906 compliant", th: "สอดคล้องกับ ISO 18901 และ ISO 18906" },
      { en: "500+ year archival lifespan", th: "อายุการใช้งานหอจดหมายเหตุ 500 ปีขึ้นไป" },
    ],
    process: [
      { en: "Microfilm Specification", th: "ข้อมูลจำเพาะไมโครฟิล์ม" },
      { en: "Document Preparation", th: "การเตรียมเอกสาร" },
      { en: "Filming Process", th: "กระบวนการถ่ายฟิล์ม" },
      { en: "Quality Inspection", th: "การตรวจสอบคุณภาพ" },
      { en: "Archival Storage", th: "การจัดเก็บหอจดหมายเหตุ" },
    ],
    pricing: [
      {
        tier: "Standard",
        price: "2.00",
        currency: "฿/page",
        description: "Basic microfilm creation",
        features: [
          "16mm microfilm",
          "Standard reduction ratio",
          "Basic quality control",
          "ISO 18901 compliant",
        ],
      },
      {
        tier: "Premium",
        price: "3.50",
        currency: "฿/page",
        description: "High-quality archival microfilm",
        features: [
          "16mm or 35mm options",
          "Optimized reduction ratio",
          "Advanced quality control",
          "ISO 18901 & 18906 compliant",
          "Archival-grade storage",
        ],
      },
      {
        tier: "Enterprise",
        price: 0,
        currency: "",
        description: "Complete microfilm solutions",
        features: [
          "COM services",
          "Microfilm duplication",
          "Microfilm scanning",
          "Reader maintenance",
          "Custom specifications",
        ],
      },
    ],
    faqs: [
      {
        question: "How long does microfilm last?",
        questionTh: "ไมโครฟิล์มอยู่ได้นานแค่ไหน?",
        answer: "ISO certified microfilm lasts 500+ years under proper storage conditions (cool, dry environment).",
        answerTh: "ไมโครฟิล์มที่ได้รับการรับรอง ISO อยู่ได้ 500 ปีขึ้นไปภายใต้เงื่อนไขการจัดเก็บที่เหมาะสม (สภาพแวดล้อมที่เย็นและแห้ง)",
      },
      {
        question: "Can we scan microfilm back to digital?",
        questionTh: "เราสามารถสแกนไมโครฟิล์มกลับเป็นดิจิทัลได้หรือไม่?",
        answer: "Yes, we offer high-resolution microfilm scanning (600-1200 DPI) to convert to digital formats.",
        answerTh: "ใช่ เรามีบริการสแกนไมโครฟิล์มความละเอียดสูง (600-1200 DPI) เพื่อแปลงเป็นรูปแบบดิจิทัล",
      },
      {
        question: "What is COM service?",
        questionTh: "บริการ COM คืออะไร?",
        answer: "COM (Computer Output Microfilm) converts digital data directly to microfilm without printing, saving time and cost.",
        answerTh: "COM (Computer Output Microfilm) แปลงข้อมูลดิจิทัลเป็นไมโครฟิล์มโดยตรงโดยไม่ต้องพิมพ์ ประหยัดเวลาและค่าใช้จ่าย",
      },
    ],
  },
  ancient: {
    titleEn: "Ancient Document Preservation",
    titleTh: "การอนุรักษ์เอกสารโบราณ",
    descriptionEn: "Expert conservation and digitization of Thailand's invaluable historical records.",
    descriptionTh: "การอนุรักษ์และการแปลงดิจิทัลของบันทึกประวัติศาสตร์อันล้ำค่าของไทยโดยผู้เชี่ยวชาญ",
    overviewEn: "Our heritage document specialists combine traditional conservation techniques with modern digitization technology. From palm leaf manuscripts to royal decrees, we handle each piece with the utmost care, ensuring preservation for future generations while making content accessible to researchers and the public.",
    overviewTh: "ผู้เชี่ยวชาญด้านเอกสารมรดกของเราผสมผสานเทคนิคการอนุรักษ์แบบดั้งเดิมกับเทคโนโลยีการแปลงดิจิทัลสมัยใหม่ ตั้งแต่สมุดข่อยจนถึงพระราชโองการ เราดูแลแต่ละชิ้นด้วยความระมัดระวังสูงสุด เพื่อให้มั่นใจว่าการอนุรักษ์สำหรับรุ่นอนาคตในขณะเดียวกันทำให้เนื้อหาเข้าถึงได้สำหรับนักวิจัยและสาธารณชน",
    ctaText: { en: "Preserve Your Heritage", th: "อนุรักษ์มรดกของคุณ" },
    benefits: [
      { en: "Condition assessment and conservation", th: "การประเมินสภาพและการอนุรักษ์" },
      { en: "Multi-spectral imaging for damaged documents", th: "การถ่ายภาพหลายสเปกตรัมสำหรับเอกสารที่เสียหาย" },
      { en: "Palm leaf manuscript digitization", th: "การแปลงดิจิทัลสมุดข่อย" },
      { en: "Archival-grade storage and housing", th: "การจัดเก็บและบรรจุภัณฑ์ระดับหอจดหมายเหตุ" },
      { en: "Digital access portals for researchers", th: "พอร์ทัลการเข้าถึงดิจิทัลสำหรับนักวิจัย" },
      { en: "UNESCO and international standards compliance", th: "การปฏิบัติตาม UNESCO และมาตรฐานระหว่างประเทศ" },
    ],
    process: [
      { en: "Heritage Assessment", th: "การประเมินมรดก" },
      { en: "Conservation Treatment", th: "การบำบัดอนุรักษ์" },
      { en: "Multi-spectral Imaging", th: "การถ่ายภาพหลายสเปกตรัม" },
      { en: "Digital Cataloging", th: "การจัดทำแคตตาล็อกดิจิทัล" },
      { en: "Research Portal Setup", th: "การตั้งค่าพอร์ทัลวิจัย" },
    ],
    pricing: [
      {
        tier: "Assessment",
        price: "10000",
        currency: "฿/item",
        description: "Condition assessment only",
        features: [
          "Professional evaluation",
          "Detailed condition report",
          "Conservation recommendations",
          "Photography included",
        ],
      },
      {
        tier: "Conservation",
        price: "50000",
        currency: "฿/item",
        description: "Full conservation treatment",
        features: [
          "Professional conservation",
          "Archival housing",
          "Detailed documentation",
          "High-resolution imaging",
        ],
      },
      {
        tier: "Complete Heritage",
        price: 0,
        currency: "",
        description: "Full preservation & digitization",
        features: [
          "Conservation + digitization",
          "Multi-spectral imaging",
          "Digital portal setup",
          "Research access",
          "UNESCO compliance",
        ],
      },
    ],
    faqs: [
      {
        question: "How do you handle fragile documents?",
        questionTh: "คุณจัดการเอกสารที่ละเอียดอ่อนอย่างไร?",
        answer: "We use specialized techniques and equipment, with trained conservators handling each item individually with extreme care.",
        answerTh: "เราใช้เทคนิคและอุปกรณ์ที่เฉพาะเจาะจง โดยมีผู้อนุรักษ์ที่ได้รับการฝึกอบรมจัดการแต่ละชิ้นด้วยความระมัดระวังสูงสุด",
      },
      {
        question: "What is multi-spectral imaging?",
        questionTh: "การถ่ายภาพหลายสเปกตรัมคืออะไร?",
        answer: "It captures images at different wavelengths to reveal hidden text and details not visible to the naked eye.",
        answerTh: "มันจับภาพที่ความยาวคลื่นต่างๆ เพื่อเปิดเผยข้อความและรายละเอียดที่ซ่อนอยู่ที่มองไม่เห็นด้วยตาเปล่า",
      },
      {
        question: "Can researchers access digitized documents?",
        questionTh: "นักวิจัยสามารถเข้าถึงเอกสารที่แปลงดิจิทัลได้หรือไม่?",
        answer: "Yes, we set up secure digital portals with controlled access for researchers and institutions.",
        answerTh: "ใช่ เราตั้งค่าพอร์ทัลดิจิทัลที่ปลอดภัยพร้อมการเข้าถึงที่ควบคุมสำหรับนักวิจัยและสถาบัน",
      },
    ],
  },
  workflow: {
    titleEn: "Workflow Automation",
    titleTh: "ระบบอัตโนมัติของขั้นตอนการทำงาน",
    descriptionEn: "Transform manual processes into intelligent automated workflows.",
    descriptionTh: "เปลี่ยนกระบวนการด้วยตนเองเป็นขั้นตอนการทำงานอัตโนมัติที่ชาญฉลาด",
    overviewEn: "Our workflow solutions reduce processing time, eliminate bottlenecks, and provide complete visibility into document status at every stage. Automated routing, approval chains, and notifications keep your organization moving efficiently.",
    overviewTh: "โซลูชันขั้นตอนการทำงานของเราลดเวลาการประมวลผล ขจัดคอขวด และให้ความโปร่งใสสมบูรณ์ในสถานะเอกสารทุกขั้นตอน การกำหนดเส้นทางอัตโนมัติ ห่วงโซ่การอนุมัติ และการแจ้งเตือนทำให้องค์กรของคุณเคลื่อนไหวได้อย่างมีประสิทธิภาพ",
    ctaText: { en: "Automate Your Workflows", th: "ทำให้ขั้นตอนการทำงานของคุณเป็นอัตโนมัติ" },
    benefits: [
      { en: "Custom workflow design", th: "การออกแบบขั้นตอนการทำงานที่กำหนดเอง" },
      { en: "Multi-level approval routing", th: "การกำหนดเส้นทางการอนุมัติหลายระดับ" },
      { en: "Real-time status tracking", th: "การติดตามสถานะแบบเรียลไทม์" },
      { en: "SLA monitoring and escalation", th: "การตรวจสอบ SLA และการยกระดับ" },
      { en: "Analytics and reporting", th: "การวิเคราะห์และการรายงาน" },
      { en: "Mobile access and notifications", th: "การเข้าถึงมือถือและการแจ้งเตือน" },
    ],
    process: [
      { en: "Process Mapping", th: "การแมปกระบวนการ" },
      { en: "Workflow Design", th: "การออกแบบขั้นตอนการทำงาน" },
      { en: "System Configuration", th: "การกำหนดค่าระบบ" },
      { en: "Testing & Optimization", th: "การทดสอบและการปรับปรุง" },
      { en: "Deployment & Training", th: "การปรับใช้และการฝึกอบรม" },
    ],
    pricing: [
      {
        tier: "Starter",
        price: "30000",
        currency: "฿/month",
        description: "For small workflows",
        features: [
          "Up to 5 workflow processes",
          "Basic automation",
          "Email notifications",
          "Monthly reporting",
        ],
      },
      {
        tier: "Professional",
        price: "75000",
        currency: "฿/month",
        description: "For growing organizations",
        features: [
          "Up to 20 workflow processes",
          "Advanced automation",
          "Mobile app access",
          "Real-time analytics",
          "Priority support",
        ],
      },
      {
        tier: "Enterprise",
        price: 0,
        currency: "",
        description: "Custom enterprise workflows",
        features: [
          "Unlimited workflows",
          "Full customization",
          "Advanced analytics",
          "API access",
          "24/7 support",
        ],
      },
    ],
    faqs: [
      {
        question: "How much time can we save?",
        questionTh: "เราสามารถประหยัดเวลาได้เท่าไร?",
        answer: "Organizations typically see 40-60% reduction in processing time and 70% fewer manual errors.",
        answerTh: "องค์กรมักจะเห็นการลดลง 40-60% ในเวลาการประมวลผลและข้อผิดพลาดด้วยตนเองน้อยลง 70%",
      },
      {
        question: "Can we integrate with our current systems?",
        questionTh: "เราสามารถรวมกับระบบปัจจุบันของเราได้หรือไม่?",
        answer: "Yes, we integrate with most enterprise systems via APIs and middleware solutions.",
        answerTh: "ใช่ เรารวมกับระบบองค์กรส่วนใหญ่ผ่าน API และโซลูชัน middleware",
      },
      {
        question: "What if we need to change a workflow?",
        questionTh: "จะเป็นอย่างไรหากเราต้องเปลี่ยนขั้นตอนการทำงาน?",
        answer: "Workflows are easily modified without coding. We provide training and support for any changes.",
        answerTh: "ขั้นตอนการทำงานสามารถแก้ไขได้อย่างง่ายดายโดยไม่ต้องเขียนโค้ด เรามีการฝึกอบรมและการสนับสนุนสำหรับการเปลี่ยนแปลงใด ๆ",
      },
    ],
  },
  conversion: {
    titleEn: "Media Conversion Services",
    titleTh: "บริการแปลงสื่อ",
    descriptionEn: "Seamless transformation between paper, electronic, and microfilm formats.",
    descriptionTh: "การแปลงระหว่างกระดาษ อิเล็กทรอนิกส์ และไมโครฟิล์มอย่างราบรื่น",
    overviewEn: "Our media conversion services enable seamless transformation between paper, electronic, and microfilm formats. Every conversion is fully reversible, ensuring your documents remain accessible in any format you need, now and in the future. This flexibility protects your investment in document management.",
    overviewTh: "บริการแปลงสื่อของเราช่วยให้การแปลงระหว่างกระดาษ อิเล็กทรอนิกส์ และไมโครฟิล์มเป็นไปอย่างราบรื่น การแปลงทุกครั้งสามารถย้อนกลับได้อย่างสมบูรณ์ เพื่อให้มั่นใจว่าเอกสารของคุณยังคงเข้าถึงได้ในรูปแบบที่คุณต้องการ ทั้งในปัจจุบันและอนาคต ความยืดหยุ่นนี้ปกป้องการลงทุนของคุณในการจัดการเอกสาร",
    ctaText: { en: "Convert Your Media", th: "แปลงสื่อของคุณ" },
    benefits: [
      { en: "Paper to electronic (scanning + OCR)", th: "กระดาษเป็นอิเล็กทรอนิกส์ (สแกน + OCR)" },
      { en: "Electronic to microfilm (COM)", th: "อิเล็กทรอนิกส์เป็นไมโครฟิล์ม (COM)" },
      { en: "Microfilm to electronic (scanning)", th: "ไมโครฟิล์มเป็นอิเล็กทรอนิกส์ (สแกน)" },
      { en: "Paper to microfilm (direct filming)", th: "กระดาษเป็นไมโครฟิล์ม (ถ่ายฟิล์มโดยตรง)" },
      { en: "All conversions fully reversible", th: "การแปลงทั้งหมดสามารถย้อนกลับได้อย่างสมบูรณ์" },
      { en: "Format flexibility for future needs", th: "ความยืดหยุ่นของรูปแบบสำหรับความต้องการในอนาคต" },
    ],
    process: [
      { en: "Format Assessment", th: "การประเมินรูปแบบ" },
      { en: "Conversion Planning", th: "การวางแผนการแปลง" },
      { en: "Media Conversion", th: "การแปลงสื่อ" },
      { en: "Quality Verification", th: "การตรวจสอบคุณภาพ" },
      { en: "Archival Storage", th: "การจัดเก็บหอจดหมายเหตุ" },
    ],
    pricing: [
      {
        tier: "Single Format",
        price: "1.50",
        currency: "฿/page",
        description: "One-way conversion",
        features: [
          "Paper to electronic",
          "Electronic to microfilm",
          "Microfilm to electronic",
          "Standard quality",
        ],
      },
      {
        tier: "Dual Format",
        price: "2.50",
        currency: "฿/page",
        description: "Two-way conversion capability",
        features: [
          "Reversible conversion",
          "Multiple format support",
          "High-quality output",
          "Archival storage",
        ],
      },
      {
        tier: "Multi-Format",
        price: 0,
        currency: "",
        description: "Complete format flexibility",
        features: [
          "All format conversions",
          "Unlimited reversibility",
          "Custom specifications",
          "Dedicated support",
        ],
      },
    ],
    faqs: [
      {
        question: "Why convert between formats?",
        questionTh: "ทำไมต้องแปลงระหว่างรูปแบบ?",
        answer: "Different formats serve different needs: microfilm for archival, electronic for access, paper for compliance.",
        answerTh: "รูปแบบที่แตกต่างกันตอบสนองความต้องการที่แตกต่างกัน: ไมโครฟิล์มสำหรับหอจดหมายเหตุ อิเล็กทรอนิกส์สำหรับการเข้าถึง กระดาษสำหรับการปฏิบัติตาม",
      },
      {
        question: "Is data quality maintained during conversion?",
        questionTh: "คุณภาพของข้อมูลได้รับการรักษาไว้ระหว่างการแปลงหรือไม่?",
        answer: "Yes, our conversion processes maintain 99.9% data integrity with rigorous quality control.",
        answerTh: "ใช่ กระบวนการแปลงของเรารักษาความสมบูรณ์ของข้อมูล 99.9% พร้อมการควบคุมคุณภาพที่เข้มงวด",
      },
      {
        question: "Can we convert back to original format?",
        questionTh: "เราสามารถแปลงกลับเป็นรูปแบบเดิมได้หรือไม่?",
        answer: "Yes, all conversions are fully reversible. You can convert between any formats as needed.",
        answerTh: "ใช่ การแปลงทั้งหมดสามารถย้อนกลับได้อย่างสมบูรณ์ คุณสามารถแปลงระหว่างรูปแบบใด ๆ ตามต้องการ",
      },
    ],
  },
};
